### ISSUE TITLE
提个小小的建议

### ISSUE THREAD

**Issue by SkipM4** [Thiasap/ClipboardFilter#3]
什么时候在应用内添加一个隐藏桌面图标的开关呢(

**Comment by Thiasap** [comment]
简单，可以搞，但是最近没空 嘿嘿有空写

**Comment by StellarHS** [comment]
没空两年了🌚

**Comment by Thiasap** [comment]
> 没空两年了🌚 这代码感觉可以复制其他模块稍微改改就行

 哈哈哈我都给忘了，我记得好像有更好的app做这个剪贴板过滤了，然后就没管了，我尽量这两天看看哈哈哈哈，不过也可以通过MyAndroidTools等类似的app禁用MainActivity来实现隐藏图标

**Comment by Thiasap** [comment]
已更新哈哈哈哈哈哈拖了两年多了
